### PR TITLE
default time_order for TimeFunction

### PR DESCRIPTION
**Pull request by samtkaplan**

### CODE REVIEW

**Comment by deckerla** [comment]
Why is the default not picked up by the underlying python method? My intuition is that enforcing what we think of as default arguments could lead to issues.

**Comment by samtkaplan** [comment]
@deckerla I agree.  Any ideas why the Python default is not picked up?

**Comment by deckerla** [comment]
I'm not sure. Do we have a mfe for the default not being picked up?

**Comment by samtkaplan** [comment]
sure, without this change:
```
using Devito

nx, ny = 100, 100
grid = Grid(shape=(nx, ny))

u = TimeFunction(name="u", grid=grid, space_order=2, save=200)
dt(u) # fails
```
However, I just noticed that if I exclude "save=200", then it works as expected.  So, perhaps there is a bug in the keyword arg handling.

**Comment by deckerla** [comment]
I would say a good test is to recreate the behavior in python. I think python Devito should behave similarly. Then submit an issue to Devito.py so they can determine the best way to deal with the issue that is consistent with the design principles of the package.

**Pull request closed without merging**
